const TYPES = {
    IUserAuthRepository: Symbol.for("IUserAuthRepository"),
    IUserAuthService: Symbol.for("IUserAuthService"),
    IUserAuthController: Symbol.for("IUserAuthController"),
    IOTPService: Symbol.for("IOTPService"),
    IJwtService: Symbol.for("IJwtService"),
    IBaseRepository: Symbol.for("IBaseRepository"),
    IEmailService: Symbol.for("IEmailService"),
    IUserProfileService: Symbol.for("IUserProfileService"),
    IUserProfileController: Symbol.for("IUserProfileController"),
    IAdminAuthRepository: Symbol.for("IAdminAuthRepository"),
    IAdminAuthService: Symbol.for("IAdminAuthService"),
    IAdminAuthController: Symbol.for("IAdminAuthController"),
    IAdminCustomerRepository: Symbol.for("IAdminCustomerRepository"),
    IAdminCustomerService: Symbol.for("IAdminCustomerService"),
    IAdminCustomerController: Symbol.for("IAdminCustomerController"),
    IAdminCategoryController: Symbol.for("IAdminCategoryController"),
    IAdminCategoryService: Symbol.for("IAdminCategoryService"),
    IAdminCategoryRepository: Symbol.for("IAdminCategoryRepository"),
    IAdminProductController: Symbol.for("IAdminProductController"),
    IAdminProductService: Symbol.for("IAdminProductService"),
    IAdminProductRepository: Symbol.for("IAdminProductRepository"),
    IUserProductRepository: Symbol.for("IUserProductRepository"),
    IUserProductService: Symbol.for("IUserProductService"),
    IUserProductController: Symbol.for("IUserProductController"),
    IUserHomeService: Symbol.for("IUserHomeService"),
    IUserHomeController: Symbol.for("IUserHomeController"),
    ICartRepository: Symbol.for("ICartRepository"),
    ICartService: Symbol.for("ICartService"),
    IUserCartController: Symbol.for("IUserCartController"),
    IWishlistRepository: Symbol.for("IWishlistRepository"),
    IWishlistService: Symbol.for("IWishlistService"),
    IUserWishlistController: Symbol.for("IUserWishlistController"),
    IUserCategoryRepository: Symbol.for("IUserCategoryRepository"),
    IUserCategoryService: Symbol.for("IUserCategoryService"),
    IUserCategoryController: Symbol.for("IUserCategoryController"),
    UserCategoryController: Symbol.for("UserCategoryController"),
    IUserAddressRepository: Symbol.for("IUserAddressRepository"),
    IUserAddressService: Symbol.for("IUserAddressService"),
    IUserAddressController: Symbol.for("IUserAddressController"),
    IUserCheckoutRepository: Symbol.for("IUserCheckoutRepository"),
    IUserCheckoutService: Symbol.for("IUserCheckoutService"),
    IUserCheckoutController: Symbol.for("IUserCheckoutController"),
    IUserOrderRepository: Symbol.for("IUserOrderRepository"),
    IUserOrderService: Symbol.for("IUserOrderService"),
    IUserOrderController: Symbol.for("IUserOrderController"),
    IAdminOrderRepository: Symbol.for("IAdminOrderRepository"),
    IAdminOrderService: Symbol.for("IAdminOrderService"),
    IAdminOrderController: Symbol.for("IAdminOrderController"),
    IAdminCouponRepository: Symbol.for("IAdminCouponRepository"),
    IAdminCouponService: Symbol.for("IAdminCouponService"),
    IAdminCouponController: Symbol.for("IAdminCouponController"),
    IUserCouponRepository: Symbol.for("IUserCouponRepository"),
    IUserCouponService: Symbol.for("IUserCouponService"),
    IUserCouponController: Symbol.for("IUserCouponController"),
    IAdminTransactionRepository: Symbol.for("IAdminTransactionRepository"),
    IAdminTransactionService: Symbol.for("IAdminTransactionService"),
    IAdminTransactionController: Symbol.for("IAdminTransactionController"),
    IAdminDashboardRepository: Symbol.for("IAdminDashboardRepository"),
    IAdminDashboardService: Symbol.for("IAdminDashboardService"),
    IAdminDashboardController: Symbol.for("IAdminDashboardController"),

    IUserReviewRepository: Symbol.for("IUserReviewRepository"),
    IUserReviewService: Symbol.for("IUserReviewService"),
    IUserReviewController: Symbol.for("IUserReviewController"),
    IAdminReviewRepository: Symbol.for("IAdminReviewRepository"),
    IAdminReviewService: Symbol.for("IAdminReviewService"),
    IAdminReviewController: Symbol.for("IAdminReviewController"),
    IWhatsappService: Symbol.for("IWhatsappService"),

    IOrderSettingsRepository: Symbol.for("IOrderSettingsRepository"),
    IOrderSettingsService: Symbol.for("IOrderSettingsService"),
    IOrderSettingsController: Symbol.for("IOrderSettingsController"),
    IAdminDeliveryRepository: Symbol.for("IAdminDeliveryRepository"),
    IAdminDeliveryService: Symbol.for("IAdminDeliveryService"),
    IAdminDeliveryController: Symbol.for("IAdminDeliveryController"),

    IFlashSaleRepository: Symbol.for("IFlashSaleRepository"),
    IFlashSaleService: Symbol.for("IFlashSaleService"),
    IFlashSaleController: Symbol.for("IFlashSaleController"),

    IFeaturedProductRepository: Symbol.for("IFeaturedProductRepository"),
    IFeaturedProductService: Symbol.for("IFeaturedProductService"),
    IFeaturedProductController: Symbol.for("IFeaturedProductController"),
};

export { TYPES };