const TYPES = {
    IUserAuthRepository: Symbol.for("IUserAuthRepository"),
    IUserAuthService: Symbol.for("IUserAuthService"),
    IUserAuthController: Symbol.for("IUserAuthController"),
    IOTPService: Symbol.for("IOTPService"),
    IJwtService: Symbol.for("IJwtService"),
    IBaseRepository: Symbol.for("IBaseRepository"),
    IEmailService: Symbol.for("IEmailService"),
    IUserProfileService: Symbol.for("IUserProfileService"),
    IUserProfileController: Symbol.for("IUserProfileController"),
    IAdminAuthRepository: Symbol.for("IAdminAuthRepository"),
    IAdminAuthService: Symbol.for("IAdminAuthService"),
    IAdminAuthController: Symbol.for("IAdminAuthController"),
    IAdminCustomerRepository: Symbol.for("IAdminCustomerRepository"),
    IAdminCustomerService: Symbol.for("IAdminCustomerService"),
    IAdminCustomerController: Symbol.for("IAdminCustomerController"),
    IAdminCategoryController: Symbol.for("IAdminCategoryController"),
    IAdminCategoryService: Symbol.for("IAdminCategoryService"),
    IAdminCategoryRepository: Symbol.for("IAdminCategoryRepository"),
    IAdminProductController: Symbol.for("IAdminProductController"),
    IAdminProductService: Symbol.for("IAdminProductService"),
    IAdminProductRepository: Symbol.for("IAdminProductRepository"),
    IUserProductRepository: Symbol.for("IUserProductRepository"),
    IUserProductService: Symbol.for("IUserProductService"),
    IUserProductController: Symbol.for("IUserProductController"),
    IUserHomeService: Symbol.for("IUserHomeService"),
    IUserHomeController: Symbol.for("IUserHomeController"),
};

export { TYPES };